// SPDX-License-Identifier: BlueOak-1.0.0
// AUTOGENERATED by formal-verification/cas/_export/foundry_regression_corpus.gp
// Do not edit by hand. Re-run the .gp script to regenerate.

pragma solidity 0.8.28;

import "forge-std/Test.sol";
import { FixLib, FIX_ONE, FIX_MAX, CEIL, FLOOR, ROUND } from "contracts/libraries/Fixed.sol";
import { ThrottleLib } from "contracts/libraries/Throttle.sol";

/// CAS-derived regression corpus. Each test corresponds to a witness
/// from formal-verification/cas/<domain>/<script>.gp.
contract CASRegression is Test {
    using FixLib for uint192;

    // ---- FixLib.safeMulDiv saturation corpus ----
    // Source: cas/fixlib/safe_muldiv_certora_witness.gp
    function test_safeMulDiv_saturates_at_minimum_overflow() public pure {
        // Minimum-overflow class: a*b/c == FIX_MAX + 1 (single-bit overshoot).
        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**96), uint192(1), CEIL)), uint256(FIX_MAX));
        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**97), uint192(2), CEIL)), uint256(FIX_MAX));
        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**98), uint192(4), CEIL)), uint256(FIX_MAX));
        // Audit's original regression input: a=2^191+1, b=2^192-2, c=2^127
        assertEq(uint256(FixLib.safeMulDiv(uint192(3138550867693340381917894711603833208051177722232017256449), uint192(6277101735386680763835789423207666416102355444464034512894), uint192(170141183460469231731687303715884105728), CEIL)), uint256(FIX_MAX));
    }

    // ---- FixLib.safeDiv FIX_MAX propagation ----
    // Source: cas/fixlib/safe_div_propagation.gp
    function test_safeDiv_FIX_MAX_propagates_across_b_range() public pure {
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(FIX_ONE), ROUND)), uint256(FIX_MAX));
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(2 * FIX_ONE), ROUND)), uint256(FIX_MAX));
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(100 * FIX_ONE), ROUND)), uint256(FIX_MAX));
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(1_000_000_000 * FIX_ONE), ROUND)), uint256(FIX_MAX));
    }

    // ---- FixLib.mul default rounding is FLOOR ----
    // Source: cas/fixlib/mul_rounding_direction.gp
    function test_mul_default_is_floor() public pure {
        // From Fixed.test.ts mulTest table after #1283:
        assertEq(uint256(FixLib.mul(uint192(15 * 1e8), uint192(45 * 1e9))), uint256(67));
        // mul(x,y) and mul(x,y,FLOOR) must agree definitionally.
        uint192 x = uint192(15 * 1e8); uint192 y = uint192(45 * 1e9);
        assertEq(uint256(FixLib.mul(x, y)), uint256(FixLib.mul(x, y, FLOOR)));
    }

    // ---- FixLib.powu boundary cases ----
    // Source: cas/fixlib/powu_correctness.gp
    function test_powu_boundary() public pure {
        assertEq(uint256(FixLib.powu(uint192(FIX_ONE / 2), uint48(0))), uint256(FIX_ONE));   // x^0 == 1
        assertEq(uint256(FixLib.powu(uint192(FIX_ONE / 2), uint48(1))), uint256(FIX_ONE / 2)); // x^1 == x
        assertEq(uint256(FixLib.powu(uint192(FIX_ONE), uint48(100))), uint256(FIX_ONE));   // 1^N == 1
        assertEq(uint256(FixLib.powu(uint192(0), uint48(0))), uint256(FIX_ONE));            // 0^0 == 1 (Solidity convention)
        assertEq(uint256(FixLib.powu(uint192(0), uint48(5))), uint256(0));                  // 0^N == 0 for N>=1
    }

    // ---- ThrottleLib cap invariant ----
    // Source: cas/throttle/cap_invariant.gp
    function test_throttle_currentlyAvailable_capped_at_limit() public {
        // Use a fresh in-memory Throttle struct via storage gymnastics in Foundry.
        // (In practice this is exercised through RTokenP1 or a wrapper test contract.)
        // Here we verify the algebraic property: at delta = ONE_HOUR with lastAvailable=0,
        // currentlyAvailable returns exactly `limit`.
        uint256 limit = 1_000_000 * FIX_ONE;
        uint48 delta = 3600;
        uint256 lastAvailable = 0;
        uint256 expected = limit; // (limit * delta) / 3600 == limit at delta=3600
        uint256 raw = lastAvailable + (limit * uint256(delta)) / 3600;
        if (raw > limit) raw = limit;
        assertEq(raw, expected);
    }

    // ---- Furnace.melt: payoutRatio computation correctness ----
    // Source: cas/furnace/melt_curve.gp
    // Verifies: payoutRatio at (ratio = 0.01% per period, N = 1 day = 86400 periods)
    // matches the closed-form 1 - (1-ratio)^N to within step-wise rounding.
    function test_furnace_payoutRatio_one_day_at_max_ratio() public pure {
        uint192 ratio = uint192(1e14); // MAX_RATIO
        uint48 N = 86400;
        uint192 oneMinusR = uint192(FIX_ONE) - ratio;
        // payoutRatio = FIX_ONE - powu(oneMinusR, N)
        uint256 payoutRatio = uint256(FIX_ONE) - uint256(FixLib.powu(oneMinusR, N));
        // CAS-derived expected value: ~99.9823% of FIX_ONE = 999823189501488433.
        // Tolerance 1e9 wei accounts for any micro-rounding shifts across solc versions.
        assertApproxEqAbs(payoutRatio, 999823189501488433, 1e9);
    }

    // ---- StRSR stake invariant: stakeRSR * stakeRate >= totalStakes * FIX_ONE ----
    // Source: cas/strsr/exchange_rate_evolution.gp
    function test_strsr_stake_invariant_at_calibrated_state() public pure {
        // Calibration: stakeRSR=100M, totalStakes=1M, stakeRate=ceil(FIX_ONE * totalStakes / stakeRSR)
        uint256 stakeRSR    = 100_000_000 * uint256(FIX_ONE);
        uint256 totalStakes =   1_000_000 * uint256(FIX_ONE);
        // stakeRate = ceil(FIX_ONE * totalStakes / stakeRSR) = 1e16 (1% of FIX_ONE)
        uint192 stakeRate = uint192((uint256(FIX_ONE) * totalStakes + stakeRSR - 1) / stakeRSR);
        // Invariant: stakeRSR * stakeRate >= totalStakes * FIX_ONE
        assertGe(stakeRSR * uint256(stakeRate), totalStakes * uint256(FIX_ONE));
    }

    // ---- Distributor.distribute share conservation ----
    // Source: cas/distributor/share_conservation.gp
    function test_distributor_conservation_canonical_shares() public pure {
        // Canonical Reserve: 4000 rTokenDist (Furnace), 6000 rsrDist (StRSR), totalShares=10000
        uint256 amount = 1_000_000 * uint256(FIX_ONE); // 1M qRTok
        uint256 totalShares = 10_000;
        uint256 tokensPerShare = amount / totalShares;
        uint256 rTokenAmount = tokensPerShare * 4000;
        uint256 rsrAmount    = tokensPerShare * 6000;
        assertLe(rTokenAmount + rsrAmount, amount);
        assertLt(amount - (rTokenAmount + rsrAmount), totalShares); // dust < totalShares
    }

}
