// SPDX-License-Identifier: BlueOak-1.0.0
// AUTOGENERATED by formal-verification/cas/_export/foundry_regression_corpus.gp
// Do not edit by hand. Re-run the .gp script to regenerate.
// pragma solidity 0.8.28;

pragma solidity 0.8.28;

import "forge-std/Test.sol";
import { FixLib, FIX_ONE, FIX_MAX, CEIL, FLOOR, ROUND } from "contracts/libraries/Fixed.sol";

/// CAS-derived regression corpus protecting the FixLib mitigations from PR #1283.
/// Generated from the witness scripts under formal-verification/cas/fixlib/.
contract FixLibCASRegression is Test {
    using FixLib for uint192;

    /// @dev safeMulDiv must saturate at FIX_MAX, not produce truncated values.
    function test_safeMulDiv_saturates_at_minimum_overflow_corpus() public pure {
        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**96), uint192(2**0), CEIL)), uint256(FIX_MAX));
        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**97), uint192(2**1), CEIL)), uint256(FIX_MAX));
        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**98), uint192(2**2), CEIL)), uint256(FIX_MAX));
        // Audit regression input: a=2^191+1, b=2^192-2, c=2^127
        assertEq(uint256(FixLib.safeMulDiv(uint192(3138550867693340381917894711603833208051177722232017256449), uint192(6277101735386680763835789423207666416102355444464034512894), uint192(170141183460469231731687303715884105728), CEIL)), uint256(FIX_MAX));
    }

    /// @dev safeDiv(FIX_MAX, b) must always return FIX_MAX for any positive b.
    function test_safeDiv_FIX_MAX_propagates_across_b_range() public pure {
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(FIX_ONE), ROUND)), uint256(FIX_MAX));  // FIX_ONE
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(2 * FIX_ONE), ROUND)), uint256(FIX_MAX));  // 2*FIX_ONE
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(100 * FIX_ONE), ROUND)), uint256(FIX_MAX));  // 100*FIX_ONE
        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(uint192(1_000_000_000) * FIX_ONE), ROUND)), uint256(FIX_MAX));  // 1e9 * FIX_ONE
    }

    /// @dev Default mul(x,y) is now FLOOR. Verify the documented disagreement examples
    /// from `mulTest` in test/libraries/Fixed.test.ts ('1.5e-9 * 4.5e-8 == 67e-18').
    function test_mul_default_is_floor() public pure {
        // From the post-mitigation expected values:
        assertEq(uint256(FixLib.mul(uint192(15 * 1e8), uint192(45 * 1e9))), uint256(67));  // 1.5e-9 * 4.5e-8 in D18 should floor to 67e-18
    }
}

// ==================== Hardhat / TS variant ====================
// describe('FixLib CAS regression corpus', () => {
//   it('safeMulDiv saturates at minimum-overflow boundary', async () => {
//     expect(await caller.safeMulDiv(2n**96n, 2n**96n, 1n, CEIL)).to.equal(MAX_UINT192);
//     expect(await caller.safeMulDiv(2n**96n, 2n**97n, 2n, CEIL)).to.equal(MAX_UINT192);
//     expect(await caller.safeMulDiv(2n**96n, 2n**98n, 4n, CEIL)).to.equal(MAX_UINT192);
//   });
//   it('safeDiv propagates FIX_MAX across b range', async () => {
//     for (const b of [FIX_ONE, 2n*FIX_ONE, 100n*FIX_ONE, 10n**9n * FIX_ONE])
//       expect(await caller.safeDiv(MAX_UINT192, b, ROUND)).to.equal(MAX_UINT192);
//   });
// });
