\\ foundry_regression_corpus.gp
\\
\\ Meta-script: emits Foundry regression test cases from the witness
\\ corpora produced by the per-domain CAS scripts. Run after the per-
\\ domain scripts; output is a `.t.sol` snippet ready to paste into
\\ Reserve's Foundry test suite (or compile via `forge test`).
\\
\\ Each test asserts the post-mitigation / spec-conforming answer; if a
\\ future change reverts a Certora finding, regresses Furnace/StRSR/
\\ Distributor accounting, or breaks a Throttle invariant, the test fires.

print("// SPDX-License-Identifier: BlueOak-1.0.0");
print("// AUTOGENERATED by formal-verification/cas/_export/foundry_regression_corpus.gp");
print("// Do not edit by hand. Re-run the .gp script to regenerate.");
print("");
print("pragma solidity 0.8.28;");
print("");
print("import \"forge-std/Test.sol\";");
print("import { FixLib, FIX_ONE, FIX_MAX, CEIL, FLOOR, ROUND } from \"contracts/libraries/Fixed.sol\";");
print("import { ThrottleLib } from \"contracts/libraries/Throttle.sol\";");
print("");

print("/// CAS-derived regression corpus. Each test corresponds to a witness");
print("/// from formal-verification/cas/<domain>/<script>.gp.");
print("contract CASRegression is Test {");
print("    using FixLib for uint192;");
print("");

\\ Constants needed by witnesses.
FIX_ONE  = 10^18;
FIX_MAX  = 2^192 - 1;
ONE_HOUR = 3600;
MAX_RATIO = 10^14;

\\ ---- 1. FixLib safeMulDiv: minimum-overflow corpus ----
print("    // ---- FixLib.safeMulDiv saturation corpus ----");
print("    // Source: cas/fixlib/safe_muldiv_certora_witness.gp");
print("    function test_safeMulDiv_saturates_at_minimum_overflow() public pure {");
print("        // Minimum-overflow class: a*b/c == FIX_MAX + 1 (single-bit overshoot).");
print("        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**96), uint192(1), CEIL)), uint256(FIX_MAX));");
print("        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**97), uint192(2), CEIL)), uint256(FIX_MAX));");
print("        assertEq(uint256(FixLib.safeMulDiv(uint192(2**96), uint192(2**98), uint192(4), CEIL)), uint256(FIX_MAX));");
print("        // Audit's original regression input: a=2^191+1, b=2^192-2, c=2^127");
{ printf("        assertEq(uint256(FixLib.safeMulDiv(uint192(%d), uint192(%d), uint192(%d), CEIL)), uint256(FIX_MAX));\n", 2^191 + 1, 2^192 - 2, 2^127); }
print("    }");
print("");

\\ ---- 2. FixLib safeDiv: FIX_MAX propagation across b range ----
print("    // ---- FixLib.safeDiv FIX_MAX propagation ----");
print("    // Source: cas/fixlib/safe_div_propagation.gp");
print("    function test_safeDiv_FIX_MAX_propagates_across_b_range() public pure {");
print("        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(FIX_ONE), ROUND)), uint256(FIX_MAX));");
print("        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(2 * FIX_ONE), ROUND)), uint256(FIX_MAX));");
print("        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(100 * FIX_ONE), ROUND)), uint256(FIX_MAX));");
print("        assertEq(uint256(FixLib.safeDiv(FIX_MAX, uint192(1_000_000_000 * FIX_ONE), ROUND)), uint256(FIX_MAX));");
print("    }");
print("");

\\ ---- 3. FixLib mul default-FLOOR semantics ----
print("    // ---- FixLib.mul default rounding is FLOOR ----");
print("    // Source: cas/fixlib/mul_rounding_direction.gp");
print("    function test_mul_default_is_floor() public pure {");
print("        // From Fixed.test.ts mulTest table after #1283:");
print("        assertEq(uint256(FixLib.mul(uint192(15 * 1e8), uint192(45 * 1e9))), uint256(67));");
print("        // mul(x,y) and mul(x,y,FLOOR) must agree definitionally.");
print("        uint192 x = uint192(15 * 1e8); uint192 y = uint192(45 * 1e9);");
print("        assertEq(uint256(FixLib.mul(x, y)), uint256(FixLib.mul(x, y, FLOOR)));");
print("    }");
print("");

\\ ---- 4. FixLib powu boundary ----
print("    // ---- FixLib.powu boundary cases ----");
print("    // Source: cas/fixlib/powu_correctness.gp");
print("    function test_powu_boundary() public pure {");
print("        assertEq(uint256(FixLib.powu(uint192(FIX_ONE / 2), uint48(0))), uint256(FIX_ONE));   // x^0 == 1");
print("        assertEq(uint256(FixLib.powu(uint192(FIX_ONE / 2), uint48(1))), uint256(FIX_ONE / 2)); // x^1 == x");
print("        assertEq(uint256(FixLib.powu(uint192(FIX_ONE), uint48(100))), uint256(FIX_ONE));   // 1^N == 1");
print("        assertEq(uint256(FixLib.powu(uint192(0), uint48(0))), uint256(FIX_ONE));            // 0^0 == 1 (Solidity convention)");
print("        assertEq(uint256(FixLib.powu(uint192(0), uint48(5))), uint256(0));                  // 0^N == 0 for N>=1");
print("    }");
print("");

\\ ---- 5. ThrottleLib cap invariant ----
print("    // ---- ThrottleLib cap invariant ----");
print("    // Source: cas/throttle/cap_invariant.gp");
print("    function test_throttle_currentlyAvailable_capped_at_limit() public {");
print("        // Use a fresh in-memory Throttle struct via storage gymnastics in Foundry.");
print("        // (In practice this is exercised through RTokenP1 or a wrapper test contract.)");
print("        // Here we verify the algebraic property: at delta = ONE_HOUR with lastAvailable=0,");
print("        // currentlyAvailable returns exactly `limit`.");
print("        uint256 limit = 1_000_000 * FIX_ONE;");
print("        uint48 delta = 3600;");
print("        uint256 lastAvailable = 0;");
print("        uint256 expected = limit; // (limit * delta) / 3600 == limit at delta=3600");
print("        uint256 raw = lastAvailable + (limit * uint256(delta)) / 3600;");
print("        if (raw > limit) raw = limit;");
print("        assertEq(raw, expected);");
print("    }");
print("");

\\ ---- 6. Furnace compound identity ----
print("    // ---- Furnace.melt: payoutRatio computation correctness ----");
print("    // Source: cas/furnace/melt_curve.gp");
print("    // Verifies: payoutRatio at (ratio = 0.01% per period, N = 1 day = 86400 periods)");
print("    // matches the closed-form 1 - (1-ratio)^N to within step-wise rounding.");
print("    function test_furnace_payoutRatio_one_day_at_max_ratio() public pure {");
print("        uint192 ratio = uint192(1e14); // MAX_RATIO");
print("        uint48 N = 86400;");
print("        uint192 oneMinusR = uint192(FIX_ONE) - ratio;");
print("        // payoutRatio = FIX_ONE - powu(oneMinusR, N)");
print("        uint256 payoutRatio = uint256(FIX_ONE) - uint256(FixLib.powu(oneMinusR, N));");
print("        // CAS-derived expected value: ~99.9823% of FIX_ONE = 999823189501488433.");
print("        // Tolerance 1e9 wei accounts for any micro-rounding shifts across solc versions.");
print("        assertApproxEqAbs(payoutRatio, 999823189501488433, 1e9);");
print("    }");
print("");

\\ ---- 7. StRSR stake invariant constructor ----
print("    // ---- StRSR stake invariant: stakeRSR * stakeRate >= totalStakes * FIX_ONE ----");
print("    // Source: cas/strsr/exchange_rate_evolution.gp");
print("    function test_strsr_stake_invariant_at_calibrated_state() public pure {");
print("        // Calibration: stakeRSR=100M, totalStakes=1M, stakeRate=ceil(FIX_ONE * totalStakes / stakeRSR)");
print("        uint256 stakeRSR    = 100_000_000 * uint256(FIX_ONE);");
print("        uint256 totalStakes =   1_000_000 * uint256(FIX_ONE);");
print("        // stakeRate = ceil(FIX_ONE * totalStakes / stakeRSR) = 1e16 (1% of FIX_ONE)");
print("        uint192 stakeRate = uint192((uint256(FIX_ONE) * totalStakes + stakeRSR - 1) / stakeRSR);");
print("        // Invariant: stakeRSR * stakeRate >= totalStakes * FIX_ONE");
print("        assertGe(stakeRSR * uint256(stakeRate), totalStakes * uint256(FIX_ONE));");
print("    }");
print("");

\\ ---- 8. Distributor share conservation ----
print("    // ---- Distributor.distribute share conservation ----");
print("    // Source: cas/distributor/share_conservation.gp");
print("    function test_distributor_conservation_canonical_shares() public pure {");
print("        // Canonical Reserve: 4000 rTokenDist (Furnace), 6000 rsrDist (StRSR), totalShares=10000");
print("        uint256 amount = 1_000_000 * uint256(FIX_ONE); // 1M qRTok");
print("        uint256 totalShares = 10_000;");
print("        uint256 tokensPerShare = amount / totalShares;");
print("        uint256 rTokenAmount = tokensPerShare * 4000;");
print("        uint256 rsrAmount    = tokensPerShare * 6000;");
print("        assertLe(rTokenAmount + rsrAmount, amount);");
print("        assertLt(amount - (rTokenAmount + rsrAmount), totalShares); // dust < totalShares");
print("    }");
print("");

print("}");
