\\ hardhat_regression_corpus.gp
\\
\\ Meta-script: emits a Hardhat regression test from the witness corpora
\\ produced by the per-domain CAS scripts. Output goes to
\\ test/libraries/CASRegression.test.ts in the protocol root and runs as
\\ part of the standard `yarn test` suite.
\\
\\ Each test asserts the post-mitigation / spec-conforming answer; if a
\\ future change reverts a Certora finding, regresses Furnace/StRSR/
\\ Distributor accounting, or breaks a Throttle invariant, the test fires.

print("// AUTOGENERATED by formal-verification/cas/_export/hardhat_regression_corpus.gp");
print("// Do not edit by hand. Re-run the .gp script to regenerate.");
print("//");
print("// CAS-derived regression corpus. Each test corresponds to a witness");
print("// from formal-verification/cas/<domain>/<script>.gp.");
print("");
print("import { expect } from 'chai'");
print("import { BigNumber, ContractFactory } from 'ethers'");
print("import { ethers } from 'hardhat'");
print("");
print("import { bn, fp } from '../../common/numbers'");
print("import { FixedCallerMock } from '../../typechain/FixedCallerMock'");
print("");
print("enum RoundingMode {");
print("  FLOOR,");
print("  ROUND,");
print("  CEIL,");
print("}");
print("");
print("const FLOOR = RoundingMode.FLOOR");
print("const ROUND = RoundingMode.ROUND");
print("const CEIL = RoundingMode.CEIL");
print("");
print("const FIX_ONE = fp(1)");
print("const FIX_MAX = bn(2).pow(192).sub(1)");
print("");
print("describe('CAS regression corpus', () => {");
print("  let FixedCaller: ContractFactory");
print("  let caller: FixedCallerMock");
print("");
print("  before(async () => {");
print("    FixedCaller = await ethers.getContractFactory('FixedCallerMock')");
print("    caller = await (<Promise<FixedCallerMock>>FixedCaller.deploy())");
print("  })");
print("");

\\ ---- 1. FixLib safeMulDiv: minimum-overflow corpus ----
print("  // Source: cas/fixlib/safe_muldiv_certora_witness.gp");
print("  it('FixLib.safeMulDiv saturates at FIX_MAX on minimum-overflow inputs', async () => {");
print("    // Minimum-overflow class: a*b/c == FIX_MAX + 1 (single-bit overshoot).");
print("    expect(");
print("      await caller.safeMulDiv(bn(2).pow(96), bn(2).pow(96), bn(1), CEIL)");
print("    ).to.equal(FIX_MAX)");
print("    expect(");
print("      await caller.safeMulDiv(bn(2).pow(96), bn(2).pow(97), bn(2), CEIL)");
print("    ).to.equal(FIX_MAX)");
print("    expect(");
print("      await caller.safeMulDiv(bn(2).pow(96), bn(2).pow(98), bn(4), CEIL)");
print("    ).to.equal(FIX_MAX)");
print("    // Audit's original regression input: a=2^191+1, b=2^192-2, c=2^127.");
print("    expect(");
print("      await caller.safeMulDiv(");
print("        bn(2).pow(191).add(1),");
print("        bn(2).pow(192).sub(2),");
print("        bn(2).pow(127),");
print("        CEIL");
print("      )");
print("    ).to.equal(FIX_MAX)");
print("  })");
print("");

\\ ---- 2. FixLib safeDiv: FIX_MAX propagation across b range ----
print("  // Source: cas/fixlib/safe_div_propagation.gp");
print("  it('FixLib.safeDiv propagates FIX_MAX across the b range', async () => {");
print("    expect(await caller.safeDiv(FIX_MAX, FIX_ONE, ROUND)).to.equal(FIX_MAX)");
print("    expect(await caller.safeDiv(FIX_MAX, FIX_ONE.mul(2), ROUND)).to.equal(FIX_MAX)");
print("    expect(await caller.safeDiv(FIX_MAX, FIX_ONE.mul(100), ROUND)).to.equal(FIX_MAX)");
print("    expect(");
print("      await caller.safeDiv(FIX_MAX, FIX_ONE.mul(1_000_000_000), ROUND)");
print("    ).to.equal(FIX_MAX)");
print("  })");
print("");

\\ ---- 3. FixLib mul default-FLOOR semantics ----
print("  // Source: cas/fixlib/mul_rounding_direction.gp");
print("  it('FixLib.mul default rounding is FLOOR (post-#1283)', async () => {");
print("    // From Fixed.test.ts mulTest table: 1.5e-9 * 4.5e-8 == 67e-18 (floor).");
print("    const x = bn(15).mul(bn(10).pow(8))");
print("    const y = bn(45).mul(bn(10).pow(9))");
print("    expect(await caller.mul(x, y)).to.equal(bn(67))");
print("    // mul(x,y) and mulRnd(x,y,FLOOR) must agree definitionally.");
print("    expect(await caller.mul(x, y)).to.equal(await caller.mulRnd(x, y, FLOOR))");
print("  })");
print("");

\\ ---- 4. FixLib powu boundary ----
print("  // Source: cas/fixlib/powu_correctness.gp");
print("  it('FixLib.powu satisfies boundary identities', async () => {");
print("    expect(await caller.powu(FIX_ONE.div(2), 0)).to.equal(FIX_ONE) // x^0 == 1");
print("    expect(await caller.powu(FIX_ONE.div(2), 1)).to.equal(FIX_ONE.div(2)) // x^1 == x");
print("    expect(await caller.powu(FIX_ONE, 100)).to.equal(FIX_ONE) // 1^N == 1");
print("    expect(await caller.powu(bn(0), 0)).to.equal(FIX_ONE) // 0^0 == 1 (Solidity convention)");
print("    expect(await caller.powu(bn(0), 5)).to.equal(bn(0)) // 0^N == 0 for N >= 1");
print("  })");
print("");

\\ ---- 5. ThrottleLib cap invariant ----
print("  // Source: cas/throttle/cap_invariant.gp");
print("  // Algebraic property of currentlyAvailable: at delta = ONE_HOUR with");
print("  // lastAvailable = 0, the recharge formula returns exactly `limit`.");
print("  it('ThrottleLib recharge formula caps at limit at full-period delta', () => {");
print("    const limit = bn(1_000_000).mul(FIX_ONE)");
print("    const delta = bn(3600)");
print("    const lastAvailable = bn(0)");
print("    const expected = limit");
print("    let raw = lastAvailable.add(limit.mul(delta).div(3600))");
print("    if (raw.gt(limit)) raw = limit");
print("    expect(raw).to.equal(expected)");
print("  })");
print("");

\\ ---- 6. Furnace compound identity ----
print("  // Source: cas/furnace/melt_curve.gp");
print("  // Verifies: payoutRatio at (ratio = MAX_RATIO = 1e14, N = 86400) matches the");
print("  // closed-form 1 - (1-ratio)^N to within step-wise rounding.");
print("  it('Furnace.melt payoutRatio at MAX_RATIO over one day matches CAS witness', async () => {");
print("    const ratio = bn(10).pow(14) // MAX_RATIO");
print("    const N = 86400");
print("    const oneMinusR = FIX_ONE.sub(ratio)");
print("    const payoutRatio = FIX_ONE.sub(await caller.powu(oneMinusR, N))");
print("    // CAS-derived expected value: ~99.9823% of FIX_ONE.");
print("    const expected = BigNumber.from('999823189501488433')");
print("    const tolerance = bn(10).pow(9) // 1e9 wei across solc-version micro-rounding.");
print("    expect(payoutRatio.sub(expected).abs().lte(tolerance)).to.equal(true)");
print("  })");
print("");

\\ ---- 7. StRSR stake invariant ----
print("  // Source: cas/strsr/exchange_rate_evolution.gp");
print("  // Stake invariant: stakeRSR * stakeRate >= totalStakes * FIX_ONE.");
print("  it('StRSR stake invariant holds at calibrated state', () => {");
print("    const stakeRSR = bn(100_000_000).mul(FIX_ONE)");
print("    const totalStakes = bn(1_000_000).mul(FIX_ONE)");
print("    // stakeRate = ceil(FIX_ONE * totalStakes / stakeRSR).");
print("    const stakeRate = FIX_ONE.mul(totalStakes).add(stakeRSR.sub(1)).div(stakeRSR)");
print("    expect(stakeRSR.mul(stakeRate).gte(totalStakes.mul(FIX_ONE))).to.equal(true)");
print("  })");
print("");

\\ ---- 8. Distributor share conservation ----
print("  // Source: cas/distributor/share_conservation.gp");
print("  // Canonical Reserve table (4000 rTokenDist, 6000 rsrDist, totalShares=10000).");
print("  it('Distributor share split conserves the input minus dust', () => {");
print("    const amount = bn(1_000_000).mul(FIX_ONE)");
print("    const totalShares = bn(10_000)");
print("    const tokensPerShare = amount.div(totalShares)");
print("    const rTokenAmount = tokensPerShare.mul(4000)");
print("    const rsrAmount = tokensPerShare.mul(6000)");
print("    expect(rTokenAmount.add(rsrAmount).lte(amount)).to.equal(true)");
print("    // Dust is bounded by totalShares.");
print("    expect(amount.sub(rTokenAmount.add(rsrAmount)).lt(totalShares)).to.equal(true)");
print("  })");
print("");

print("})");
