// AUTOGENERATED by formal-verification/cas/_export/hardhat_regression_corpus.gp
// Do not edit by hand. Re-run the .gp script to regenerate.
//
// CAS-derived regression corpus. Each test corresponds to a witness
// from formal-verification/cas/<domain>/<script>.gp.

import { expect } from 'chai'
import { BigNumber, ContractFactory } from 'ethers'
import { ethers } from 'hardhat'

import { bn, fp } from '../../common/numbers'
import { FixedCallerMock } from '../../typechain/FixedCallerMock'

enum RoundingMode {
  FLOOR,
  ROUND,
  CEIL,
}

const FLOOR = RoundingMode.FLOOR
const ROUND = RoundingMode.ROUND
const CEIL = RoundingMode.CEIL

const FIX_ONE = fp(1)
const FIX_MAX = bn(2).pow(192).sub(1)

describe('CAS regression corpus', () => {
  let FixedCaller: ContractFactory
  let caller: FixedCallerMock

  before(async () => {
    FixedCaller = await ethers.getContractFactory('FixedCallerMock')
    caller = await (<Promise<FixedCallerMock>>FixedCaller.deploy())
  })

  // Source: cas/fixlib/safe_muldiv_certora_witness.gp
  it('FixLib.safeMulDiv saturates at FIX_MAX on minimum-overflow inputs', async () => {
    // Minimum-overflow class: a*b/c == FIX_MAX + 1 (single-bit overshoot).
    expect(
      await caller.safeMulDiv(bn(2).pow(96), bn(2).pow(96), bn(1), CEIL)
    ).to.equal(FIX_MAX)
    expect(
      await caller.safeMulDiv(bn(2).pow(96), bn(2).pow(97), bn(2), CEIL)
    ).to.equal(FIX_MAX)
    expect(
      await caller.safeMulDiv(bn(2).pow(96), bn(2).pow(98), bn(4), CEIL)
    ).to.equal(FIX_MAX)
    // Audit's original regression input: a=2^191+1, b=2^192-2, c=2^127.
    expect(
      await caller.safeMulDiv(
        bn(2).pow(191).add(1),
        bn(2).pow(192).sub(2),
        bn(2).pow(127),
        CEIL
      )
    ).to.equal(FIX_MAX)
  })

  // Source: cas/fixlib/safe_div_propagation.gp
  it('FixLib.safeDiv propagates FIX_MAX across the b range', async () => {
    expect(await caller.safeDiv(FIX_MAX, FIX_ONE, ROUND)).to.equal(FIX_MAX)
    expect(await caller.safeDiv(FIX_MAX, FIX_ONE.mul(2), ROUND)).to.equal(FIX_MAX)
    expect(await caller.safeDiv(FIX_MAX, FIX_ONE.mul(100), ROUND)).to.equal(FIX_MAX)
    expect(
      await caller.safeDiv(FIX_MAX, FIX_ONE.mul(1_000_000_000), ROUND)
    ).to.equal(FIX_MAX)
  })

  // Source: cas/fixlib/mul_rounding_direction.gp
  it('FixLib.mul default rounding is FLOOR (post-#1283)', async () => {
    // From Fixed.test.ts mulTest table: 1.5e-9 * 4.5e-8 == 67e-18 (floor).
    const x = bn(15).mul(bn(10).pow(8))
    const y = bn(45).mul(bn(10).pow(9))
    expect(await caller.mul(x, y)).to.equal(bn(67))
    // mul(x,y) and mulRnd(x,y,FLOOR) must agree definitionally.
    expect(await caller.mul(x, y)).to.equal(await caller.mulRnd(x, y, FLOOR))
  })

  // Source: cas/fixlib/powu_correctness.gp
  it('FixLib.powu satisfies boundary identities', async () => {
    expect(await caller.powu(FIX_ONE.div(2), 0)).to.equal(FIX_ONE) // x^0 == 1
    expect(await caller.powu(FIX_ONE.div(2), 1)).to.equal(FIX_ONE.div(2)) // x^1 == x
    expect(await caller.powu(FIX_ONE, 100)).to.equal(FIX_ONE) // 1^N == 1
    expect(await caller.powu(bn(0), 0)).to.equal(FIX_ONE) // 0^0 == 1 (Solidity convention)
    expect(await caller.powu(bn(0), 5)).to.equal(bn(0)) // 0^N == 0 for N >= 1
  })

  // Source: cas/throttle/cap_invariant.gp
  // Algebraic property of currentlyAvailable: at delta = ONE_HOUR with
  // lastAvailable = 0, the recharge formula returns exactly `limit`.
  it('ThrottleLib recharge formula caps at limit at full-period delta', () => {
    const limit = bn(1_000_000).mul(FIX_ONE)
    const delta = bn(3600)
    const lastAvailable = bn(0)
    const expected = limit
    let raw = lastAvailable.add(limit.mul(delta).div(3600))
    if (raw.gt(limit)) raw = limit
    expect(raw).to.equal(expected)
  })

  // Source: cas/furnace/melt_curve.gp
  // Verifies: payoutRatio at (ratio = MAX_RATIO = 1e14, N = 86400) matches the
  // closed-form 1 - (1-ratio)^N to within step-wise rounding.
  it('Furnace.melt payoutRatio at MAX_RATIO over one day matches CAS witness', async () => {
    const ratio = bn(10).pow(14) // MAX_RATIO
    const N = 86400
    const oneMinusR = FIX_ONE.sub(ratio)
    const payoutRatio = FIX_ONE.sub(await caller.powu(oneMinusR, N))
    // CAS-derived expected value: 99.9823189...% of FIX_ONE. Exact match against
    // the production solc; if a future solc/optimizer change shifts this even by
    // one wei the test fails and we want to investigate, not paper over.
    const expected = BigNumber.from('999823189501488433')
    expect(payoutRatio).to.equal(expected)
  })

  // Source: cas/strsr/exchange_rate_evolution.gp
  // Stake invariant: stakeRSR * stakeRate >= totalStakes * FIX_ONE.
  it('StRSR stake invariant holds at calibrated state', () => {
    const stakeRSR = bn(100_000_000).mul(FIX_ONE)
    const totalStakes = bn(1_000_000).mul(FIX_ONE)
    // stakeRate = ceil(FIX_ONE * totalStakes / stakeRSR).
    const stakeRate = FIX_ONE.mul(totalStakes).add(stakeRSR.sub(1)).div(stakeRSR)
    expect(stakeRSR.mul(stakeRate).gte(totalStakes.mul(FIX_ONE))).to.equal(true)
  })

  // Source: cas/distributor/share_conservation.gp
  // Canonical Reserve table (4000 rTokenDist, 6000 rsrDist, totalShares=10000).
  it('Distributor share split conserves the input minus dust', () => {
    const amount = bn(1_000_000).mul(FIX_ONE)
    const totalShares = bn(10_000)
    const tokensPerShare = amount.div(totalShares)
    const rTokenAmount = tokensPerShare.mul(4000)
    const rsrAmount = tokensPerShare.mul(6000)
    expect(rTokenAmount.add(rsrAmount).lte(amount)).to.equal(true)
    // Dust is bounded by totalShares.
    expect(amount.sub(rTokenAmount.add(rsrAmount)).lt(totalShares)).to.equal(true)
  })

})
