(** * Fixed_yul_equiv.v — probe for Yul-equivalence proofs against FixLib

    Status: SKIPPED (substrate gap).

    This file documents an exploration: can we write a Yul-equivalence
    lemma in this repo of the upstream form

        Lemma run_FixLib_plus codes environment state (x y : U256.t) :
          uint192_valid x -> uint192_valid y ->
          x + y <= FIX_MAX ->
          {{? codes, environment, Some state |
            FixLib.plus(x, y) ⇓ Result.Ok (x + y)
          | Some state ?}}.

    It cannot, for a structural reason. Diagnostic below.

    The file deliberately contains no [Admitted]/[admit] and does not
    register itself in [_RocqProject]; it serves only as a written
    record. To re-enable it later, add it to [_RocqProject] once the
    substrate gap is closed (see the "What is missing" section below).

    ----------------------------------------------------------------
    ** What the upstream template needs

    The upstream Yul-equivalence proof template
    ([rocq-of-solidity/.../erc20/proofs/contract.v]) proves lemmas of
    the shape

        Lemma run_checked_add_uint256 codes environment state :
          {{? codes, environment, state |
            Erc20_403.checked_add_uint256 0 ⇓
            Result.Ok 20
          | state ?}}.

    The left-hand side [Erc20_403.checked_add_uint256 0] is a Rocq
    [Definition] of type [U256.t -> M.t U256.t], living in the
    *shallow* companion file [erc20/shallow.v]:

        Module Erc20_403.
          Definition checked_add_uint256 (x : U256.t) : M.t U256.t := ...

    The proof discharges by [unfold] of that [Definition] followed by
    repeated application of monadic-step tactics ([lu], [cu], [p],
    [pr], [c], [s], [l]). Crucially, the LHS reduces to a concrete
    [LowM.t] term that the [RunO.t] constructors can structurally
    consume.

    ** What this repo has

    Our auto-translated harnesses ([FurnaceMathHarness.v],
    [ThrottleHarness.v]) contain *only* the deep encoding: each Yul
    function appears as a [Code.Function.make ("checked_add_uint256",
    ...)] entry inside [Code.functions], wrapped in [M.scope],
    [M.assign], [M.call_function], etc.

    There is no [Definition FixLib.plus : U256.t -> U256.t -> M.t
    U256.t]. There is no [Definition checked_add_uint256] at the top
    level. The only way to invoke the Yul function from a [RunO.t]
    judgement is through [LowM.CallFunction "checked_add_uint256" [x;
    y] k], whose semantics (per the [RunO.CallFunction] constructor)
    require resolving [Codes.get_function codes environment
    "checked_add_uint256"] symbolically against the [codes] list.

    ** Why this blocks the requested lemma shape

    The requested lemma writes the LHS as [FixLib.plus(x, y)]. There
    is no such Rocq term: [FixLib.plus] does not exist as a
    [Definition], because the Solidity [library FixLib] is inlined
    by [solc] before reaching the Yul stage. In the Yul output, the
    [plus] body is fused into each caller's [checked_add_uint256] (or
    inlined further still). The only externally-named Yul function is
    [checked_add_uint256], and even that exists only as an AST entry
    inside [FurnaceMathHarness.deployed.code.functions].

    A proof in the upstream shape therefore requires either:

    (a) A shallow companion file (e.g.
        [FurnaceMathHarness_shallow.v]) generated by
        [rocq-of-solidity] alongside the deep harness — providing
        top-level [Definition]s for each named Yul function. This
        repo's harness generation does not produce such a file.

    (b) An indirect lemma about [LowM.CallFunction], discharged by
        unfolding [Codes.get_function] against the concrete [codes :
        list Code.t] and reducing the function body. This is
        feasible but is roughly an order of magnitude more work per
        function than the upstream shape, and was out of scope for
        the 15-minute probe.

    ** Distinction from the earlier [Throttle.useAvailable] block

    The previous Yul-equivalence attempt on [Throttle.useAvailable]
    was blocked by [Stdlib.timestamp] reducing to [LowM.Impossible
    "timestamp"], for which [RunO.t] has no constructor. That
    blocker was *semantic*: even with a shallow definition in hand,
    the proof could not close because the runtime model has no
    interpretation of [block.timestamp].

    The blocker here is different and *structural*: there is no
    shallow [Definition] to write the LHS against. FixLib's pure
    arithmetic functions ([plus], [minus], [mul], [div], [powu]) do
    not touch [block.timestamp]; if a shallow file were generated,
    the upstream tactic suite ([lu], [cu], [p], [pr], [c], [s], [l],
    plus the boundedness side conditions discharged by [lia]) would
    almost certainly close [run_FixLib_plus] in a few lines, as it
    does for [Erc20_403.checked_add_uint256] upstream.

    ** Concrete next step (if revived)

    Generate shallow companions by extending the [rocq-of-solidity]
    pipeline (or hand-writing one for FixLib's pure functions) and
    re-attempt this lemma against the new top-level [Definition].
    Until then, all FixLib reasoning in this repo runs against
    [simulations/Fixed.v] only — i.e., we trust the
    Solidity->simulation translation but do not cross-check it
    against the deep Yul AST. *)
